### ISSUE TITLE
tau reiks daryti sita savarankiska?

### ISSUE THREAD

**Issue by kebas3** [EggsDuty/HTML-CSS#1]

**Comment by EggsDuty** [comment]
nzn as kaip ir padares realiai. nesusitariau nedaryti, bet gal parodysiu sita tiesiog kai reikes. ateik paziureti mano nuostabia svetaine, kai baigs ji kalbeti

**Comment by kebas3** [comment]
tai jauciu reikalavimai tie patys tai free pazimys

**Comment by kebas3** [comment]
pazymys*

**Comment by EggsDuty** [comment]
nu ne visai tie patys. realiai pas mane sunkiau buvo ir daugiau reikalavimu

**Comment by kebas3** [comment]
[https://tavomama.lt/](url)

**Comment by EggsDuty** [comment]
[https://stud.if.ktu.lt/~taumil1](https://stud.if.ktu.lt/~taumil1)

**Comment by EggsDuty** [comment]
![image](https://user-images.githubusercontent.com/113368248/203748915-fd3de757-7bc4-4d1e-9327-b2055e5ab8a0.png)

**Comment by EggsDuty** [comment]
[https://wordpress.org/plugins/gmap-embed/](https://wordpress.org/plugins/gmap-embed/)

**Comment by EggsDuty** [comment]
[https://wpgooglemap.com/documentation/how-to-add-google-map-in-your-wordpress-post-copy/?utm_source=wp_repo&utm_medium=readme_link&utm_campaign=readme_doc_list](https://wpgooglemap.com/documentation/how-to-add-google-map-in-your-wordpress-post-copy/?utm_source=wp_repo&utm_medium=readme_link&utm_campaign=readme_doc_list)
